#!/bin/bash

type="$1"
theme="$2"

usage() {
cat <<EOF
USAGE:
$0 <type> <theme>

type: can be one of [colorful, slate, misc]
theme: a theme for the type of launcher chosen
EOF
}

if [ -z $type ]; then
    usage
    exit 1
fi

dir="$HOME/.config/rofi/launchers/$type"

if [ ! -f "$dir/themes/$theme.rasi" ]; then
    usage
    echo "Theme '$theme' does not exist!"
    echo -e "valid themes include:\n"
    ls "$dir/themes/" | sed -e "s/.rasi//g"
    exit 1
fi

rofi -no-lazy-grab -show drun -modi drun -theme "$dir/themes/$theme.rasi"
