local opt = vim.opt
local g = vim.g

g.root_spec = { ".projectroot", "lsp", ".git", "cwd" }
opt.shell = "/bin/zsh"
opt.inccommand = "split"
opt.hlsearch = true
opt.incsearch = true
opt.number = true
opt.relativenumber = true
opt.hidden = true
opt.mouse = "a"
opt.breakindent = true
opt.autoindent = true
opt.smarttab = true
opt.expandtab = true
opt.shiftround = true
opt.shiftwidth = 4
opt.softtabstop = 4
opt.tabstop = 4
opt.undodir = { vim.fn.stdpath("state") .. "/undo//" }
opt.backupdir = { vim.fn.stdpath("state") .. "/backup//" }
opt.directory = { vim.fn.stdpath("state") .. "/swap//" }
opt.undofile = true
opt.backup = true
opt.swapfile = true
opt.undoreload = 10000
opt.timeout = true
opt.ttimeout = true
opt.timeoutlen = 500
opt.ttimeoutlen = 0
opt.ignorecase = true
opt.smartcase = true
opt.gdefault = true
opt.showmatch = true
opt.showmode = false
opt.cmdheight = 1
opt.list = true
opt.listchars = {
  extends = "»",
  precedes = "«",
  tab = "│·",
  eol = "¬",
  nbsp = ".",
  trail = ".",
}
opt.wildmenu = true
opt.wildignorecase = true
opt.wildignore = "*/.git/*,*/.hg/*,*/.svn/*,*.bmp,*.gif,*.mp3,*.wav,*.wav,*.class,*.o,*.pyc,*.beam"
opt.splitbelow = true
opt.splitright = true
opt.wrap = false
opt.completeopt = "menuone,noinsert,noselect"
opt.titlestring = "%t"
opt.termguicolors = true
opt.spell = false
opt.signcolumn = "auto"

g.mapleader = " " -- sets vim.g.mapleader
g.autoformat_enabled = true -- enable or disable auto formatting at start (lsp.formatting.format_on_save must be enabled)
g.cmp_enabled = true -- enable completion at start
g.autopairs_enabled = true -- enable autopairs at start
g.diagnostics_mode = 3 -- set the visibility of diagnostics in the UI (0=off, 1=only show in status line, 2=virtual text off, 3=all on)
g.icons_enabled = true -- disable icons in the UI (disable if no nerd font is available, requires :PackerSync after changing)
g.ui_notifications_enabled = true -- disable notifications when toggling UI elements
g.editorconfig = true
