#!/usr/bin/env bash

# You can call this script like this:
# $ ./brightnessControl.sh up
# $ ./brightnessControl.sh down

# Script inspired by these wonderful people:
# https://github.com/dastorm/volume-notification-dunst/blob/master/volume.sh
# https://gist.github.com/sebastiencs/5d7227f388d93374cebdf72e783fbd6a

function get_brightness {
    current=$(brightnessctl g)
    max=$(brightnessctl m)
    echo "scale=1;$current/$max*100" | bc | cut -f1 -d .
}

function send_notification {
    icon="$HOME/.config/i3/scripts/svg/brightness.svg"
    brightness=$(get_brightness)
    # Make the bar with the special character ─ (it's not dash -)
    # https://en.wikipedia.org/wiki/Box-drawing_character
    bar=$(seq -s "─" 0 $((brightness / 5)) | sed 's/[0-9]//g')
    echo $bar
    # Send the notification
    dunstify -i "$icon" -r 5555 -u normal "    $bar"
}

case $1 in
    up)
        # increase the backlight by 5%
        brightnessctl set +5% > /dev/null
        send_notification
        ;;
    down)
        # decrease the backlight by 5%
        brightnessctl set 5%- > /dev/null
        send_notification
        ;;
esac
