#!/bin/bash

choices="Cancel\nShutdown\nReboot\nLogout"
dmenu="rofi -dmenu"

choice=$(echo -e "$choices" | $dmenu -i -p "> ")

case $choice in
    Cancel)
        ;;
    Shutdown)
        systemctl poweroff
        ;;
    Reboot)
        systemctl reboot
        ;;
    Logout)
        i3-msg exit
esac

