return {}
-- return {
--   "nvim-telescope/telescope.nvim",
--   opts = function(_, opts)
--     local actions = require("telescope.actions")
--
--     opts.defaults = vim.tbl_extend("force", opts.defaults, {
--       path_display = { "truncate" },
--       sorting_strategy = "ascending",
--       mappings = {
--         i = {
--           ["<C-n>"] = actions.cycle_history_next,
--           ["<C-p>"] = actions.cycle_history_prev,
--           ["<C-j>"] = actions.move_selection_next,
--           ["<C-k>"] = actions.move_selection_previous,
--         },
--       },
--       layout_config = {
--         horizontal = { prompt_position = "top", preview_width = 0.55 },
--         vertical = { mirror = false },
--         width = 0.87,
--         height = 0.80,
--         preview_cutoff = 120,
--       },
--     })
--   end,
-- }
